### ISSUE TITLE
[Bug] `Bridge#runServerConsoleCommand` throws `UnsupportedOperationException`

### ISSUE THREAD

**Issue by bivashy** [Phoenix616/ConnectorPlugin#10]
### What is happening?

When we execute `cpb servercommand mc playername`, or call `Bridge#runServerConsoleCommand` `UnsupportedOperationException` will occur.

### What did you expect to happen?

`Bridge#runServerConsoleCommand` should provide server id when calling `sendData`
https://github.com/Phoenix616/ConnectorPlugin/blob/6c85351f09e358a99370754ca375c995f5c33aa3/core/src/main/java/de/themoep/connectorplugin/BridgeCommon.java#L171-L173

### Version

1.5.2-SNAPSHOT (build 89)

### Config

```YAML
Proxy configuration:

# Plugin debugging
debug: true

# Currently supported types:
# - "plugin_messages" (will not be able to send messages to other proxies or servers without any players online, messages will be queued)
# - "redis" (does not require any online players)
# - "mqtt" (does not require any online players)
messenger-type: plugin_messages

# Redis messenger settings
redis:
  host: localhost
  port: 6379
  db: 0
  timeout: 60
  password: password1
  
# Mqtt messenger settings
mqtt:
  broker-uri: tcp://localhost:1883
  keep-alive: 30
  username: mqttuser
  password: password1


Server configuration

```yaml
# Plugin debugging
debug: true

# Currently supported types:
# - "plugin_messages" (will not be able to send messages from server without any players online)
# - "redis" (does not require online players)
# - "mqtt" (does not require online players)
messenger-type: plugin_messages

# The group this server is in
group: global

# Put specific plugins into different groupings
plugin-groups:
  pluginname: specialgroup

# Should be the same name as in the proxy config
server-name: mc

# Redis messenger settings
redis:
  host: localhost
  port: 6379
  db: 0
  timeout: 60
  password: password1

# Mqtt messenger settings
mqtt:
  broker-uri: tcp://localhost:1883
  keep-alive: 30
  username: mqttuser
  password: password1

```

### Server/system Version

Purpur version git-Purpur-2095 (MC: 1.20.2), git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579

### Log

```shell
java.lang.UnsupportedOperationException: Could not send data to SERVER as target server wasn't found from !
        at de.themoep.connectorplugin.bungee.connector.PluginMessageConnector.sendDataImplementation(PluginMessageConnector.java:147) ~[?:?]
        at de.themoep.connectorplugin.bungee.connector.BungeeConnector.sendDataImplementation(BungeeConnector.java:51) ~[?:?]
        at de.themoep.connectorplugin.connector.Connector.sendDataInternal(Connector.java:139) ~[?:?]
        at de.themoep.connectorplugin.connector.Connector.sendData(Connector.java:130) ~[?:?]
        at de.themoep.connectorplugin.connector.Connector.sendData(Connector.java:106) ~[?:?]
        at de.themoep.connectorplugin.BridgeCommon.sendData(BridgeCommon.java:246) ~[?:?]
        at de.themoep.connectorplugin.BridgeCommon.runServerConsoleCommand(BridgeCommon.java:172) ~[?:?]
        at de.themoep.connectorplugin.bungee.commands.ServerConsoleCommand.run(ServerConsoleCommand.java:61) ~[?:?]
        at de.themoep.connectorplugin.bungee.plugin.PluginCommand.execute(PluginCommand.java:100) ~[?:?]
        at de.themoep.connectorplugin.bungee.commands.SubCommand.run(SubCommand.java:66) ~[?:?]
        at de.themoep.connectorplugin.bungee.plugin.PluginCommand.execute(PluginCommand.java:100) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:213) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:164) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at fr.orblazer.bungeeRcon.server.RconHandler.handleCommand(RconHandler.java:82) ~[?:?]
        at fr.orblazer.bungeeRcon.server.RconHandler.channelRead0(RconHandler.java:57) ~[?:?]
        at fr.orblazer.bungeeRcon.server.RconHandler.channelRead0(RconHandler.java:13) ~[?:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

### What other programs/plugins are you running?

[bungee-rcon](https://github.com/orblazer/bungee-rcon)

### Additional context

None

**Comment by Phoenix616** [comment]
Really weird how I didn't notice that before 🤔 Probably because I don't use plugin messages.
