### ISSUE TITLE
ConnectorPlugin cannot connect to Redis

### ISSUE THREAD

**Issue by Castafers** [Phoenix616/ConnectorPlugin#2]
#### Config

 ```# Plugin debugging
debug: true

# Currently supported types:
# - "plugin_messages" (will not be able to send messages from server without any players online)
# - "redis" (does not require online players)
# - "mqtt" (does not require online players)
messenger-type: redis

# The group this server is in
group: global

# Should be the same name as in the proxy config
server-name: glevmaya

# Redis messenger settings
redis:
  host: localhost
  port: 6379
  db: 60
  timeout: 60
  password: XXX

# Mqtt messenger settings
mqtt:
  broker-uri: tcp://localhost:1883
  keep-alive: 30
  username: mqttuser
  password: password1
 ```
 
#### Environment description

 
Windows 11, MySQL 8.0.27, PHP 8.1.0, Redis 6.2, JDK 17, ConnectorPlugin (latest as of right now), Paper 1.18, Velocity 1.18

#### Full Log

```
[16:11:27 ERROR]: Error occurred while enabling ConnectorPlugin v1.2.1-SNAPSHOT (build 43) (Is it up to date?)
de.themoep.connectorplugin.lib.lettuce.core.RedisConnectionException: Unable to connect to localhost/<unresolved>:6379
        at de.themoep.connectorplugin.lib.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:330) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.lettuce.core.RedisClient.connectPubSub(RedisClient.java:363) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.connector.RedisConnection.<init>(RedisConnection.java:71) ~[ConnectorPlugin.jar:?]        at de.themoep.connectorplugin.bukkit.connector.RedisConnector.<init>(RedisConnector.java:37) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.bukkit.BukkitConnectorPlugin.onEnable(BukkitConnectorPlugin.java:68) ~[ConnectorPlugin.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:729) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:505) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:315) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: de.themoep.connectorplugin.lib.lettuce.core.RedisCommandExecutionException: ERR Client sent AUTH, but no password is set
        at de.themoep.connectorplugin.lib.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:137) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:110) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:111) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:746) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.lettuce.core.pubsub.PubSubCommandHandler.complete(PubSubCommandHandler.java:167) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:681) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.lettuce.core.pubsub.PubSubCommandHandler.decode(PubSubCommandHandler.java:112) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:598) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[ConnectorPlugin.jar:?]
        at de.themoep.connectorplugin.lib.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[ConnectorPlugin.jar:?]
        ... 1 more
[16:11:27 INFO]: [ConnectorPlugin] Disabling ConnectorPlugin v1.2.1-SNAPSHOT (build 43)
[16:11:27 ERROR]: Error occurred while disabling ConnectorPlugin v1.2.1-SNAPSHOT (build 43) (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "de.themoep.connectorplugin.bukkit.connector.BukkitConnector.close()" because "this.connector" is null
        at de.themoep.connectorplugin.bukkit.BukkitConnectorPlugin.onDisable(BukkitConnectorPlugin.java:82) ~[ConnectorPlugin.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:376) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:729) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:505) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:315) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

#### What is happening?

Everything is running properly, and I've confirmed the redis server is online, however connectorplugin isn't connecting to it upon startup

#### What did you expect to happen?

Connectorplugin connecting to redis

#### Additional info

We tried disabling the firewall, still no luck.

**Comment by Phoenix616** [comment]
Well according to the error it can't resolve `localhost` to any IP so either check what's up with that or use the actual IP/a resolveable hostname in the config.

Seeing as you are running Windows (and a non server version of that) I can't really help more than that.

**Comment by Castafers** [comment]
I forgot to mention I did try 127.0.0.1, and it came up with same error. The velocity config is 127.0.0.1

**Comment by Castafers** [comment]
Oh, I haven't tried 0.0.0.0 yet though, I'll try that
